#!/usr/bin/env bash

export HOMEBREW_NO_ANALYTICS="1"
export HOMEBREW_NO_INSECURE_REDIRECT="1"
export HOMEBREW_CASK_OPTS="--require-sha"

if command -v /opt/homebrew/bin/brew >/dev/null 2>&1; then
  BREW_PREFIX="$(/opt/homebrew/bin/brew --prefix)"
  export BREW_PREFIX
  export PATH="${BREW_PREFIX}/opt/curl/bin:${BREW_PREFIX}/sbin:${BREW_PREFIX}/bin:${PATH}"

  [[ -r "${BREW_PREFIX}/etc/profile.d/bash_completion.sh" ]] && . "${BREW_PREFIX}/etc/profile.d/bash_completion.sh"
fi
