#!/usr/bin/env bash

if command -v colima > /dev/null 2>&1; then
    alias d="nerdctl"

    colima_sidecars_up() {
        printf "==> Start sidecars\n"

        nerdctl run --name postgres -p 127.0.0.1:5432:5432 -e POSTGRES_PASSWORD=pwd -d postgres:15-alpine
        nerdctl run --name redis -p 127.0.0.1:6379:6379 -d redis:7-alpine
    }

    colima_sidecars_start() {
        printf "==> Start sidecars\n"

        nerdctl start postgres
        nerdctl start redis
    }

    colima_sidecars_stop() {
        printf "==> Shutdown sidecars\n"

        nerdctl stop postgres
        nerdctl stop redis
    }

    colima_sidecars_down() {
        colima_sidecars_stop

        printf "==> Destroy sidecars\n"

        nerdctl rm postgres
        nerdctl rm redis
    }

    colima_k8s_up() {
        printf "==> Start colima with containerd + kubernetes\n"

        colima start --runtime containerd --kubernetes --kubernetes-disable=servicelb,traefik,metrics-server
    }

    colima_down() {
        printf "==> Destroy colima\n"

        colima delete --force
    }

    colima_up() {
        printf "==> Start colima with containerd\n"

        colima start --runtime containerd --cpu 4 --memory 8 --disk 30 --vm-type vz  --vz-rosetta --mount-type virtiofs
    }

    colima_docker_up() {
        printf "==> Start colima with docker\n"

        colima start --runtime docker
    }
fi
