#!/usr/bin/env bash

if [ -d "${HOME}/opt/bin" ]; then
    export PATH="${PATH}:${HOME}/opt/bin/"
fi

# Use by TMUXG
export EDITOR='vim'

meuhteo() {
  curl -qsSL --max-time 10 "wttr.in/${1:-Paris}?m&format=v2"
}

gg_root() {
  cd $(git root)
}

__prompt_kube_display_enable () {
  export DOTFILES_PROMPT_KUBE=true
}

__prompt_kube_display_disable () {
  export DOTFILES_PROMPT_KUBE=false
}

ccd() {
  if [[ ! -f $1 && ! -d $1 ]]
  then
    echo "Can not go to '$1' => Not found"
  fi

  if [[ -f $1 ]]
  then
    cd $(dirname $1)
  else
    cd $1
  fi
}

ssh_pass() {
  ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no $1
}
