#!/usr/bin/env bash

if [ -d "${HOME}/opt/bin" ]; then
    export PATH="${PATH}:${HOME}/opt/bin"
fi

# Use by TMUX
export EDITOR='vim'

# In order to get date in history command
export HISTTIMEFORMAT="%d/%m/%y %T "

meuhteo() {
  curl --disable --max-time 30 "wttr.in/${1:-Paris}?m&format=v2"
}

gcd() {
  cd $(git root)
}

# fcd [depth] - depth is the number of sub-levels to descend (default 0, -1 for all)
fcd() {
  local depth="${1:-0}"

  if [[ "${depth}" == "-1" ]]
  then
    ccd $(find . | fzf)
  else
    ccd $(find . -maxdepth $((depth + 1)) | fzf)
  fi
}

alias ffcd="fcd -1"

facd() {
  ccd $(find . -type d | fzf)
}

ccd() {
  if [[ ! -f $1 && ! -d $1 ]]
  then
    echo "Can not go to '$1' => Not found"
  else
    if [[ -f $1 ]]
    then
      cd $(dirname $1)
    else
      cd $1
    fi
  fi
}

ssh_pass() {
  ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no $1
}

_ff_search_g() {
  firefox --new-tab "https://www.google.com/search?q=$1"
}

alias curl_r3="CURL_SSL_BACKEND=secure-transport curl"
