#!/usr/bin/env bash

# The next line updates PATH for the Google Cloud SDK.
if [ -f "${HOME}/opt/google-cloud-sdk/path.bash.inc" ]; then . "${HOME}/opt/google-cloud-sdk/path.bash.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "${HOME}/opt/google-cloud-sdk/completion.bash.inc" ]; then . "${HOME}/opt/google-cloud-sdk/completion.bash.inc"; fi

gcloud_auth() {
  rm -rf "/tmp/${USER}*"
  gcloud auth login --no-launch-browser

  gcloud config unset compute/region
  gcloud config set project "$(gcloud projects list | grep dev | awk '{print $1}')"

  gcloud config set disable_usage_reporting false

  if command -v docker > /dev/null 2>&1; then
    gcloud --quiet auth configure-docker
  fi
}

if command -v gcloud > /dev/null 2>&1; then
  alias __gcloud_projects_list="gcloud projects list"
fi

