#!/usr/bin/env bash

# The next line updates PATH for the Google Cloud SDK.
if [ -f "${HOME}/opt/google-cloud-sdk/path.bash.inc" ]; then . "${HOME}/opt/google-cloud-sdk/path.bash.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "${HOME}/opt/google-cloud-sdk/completion.bash.inc" ]; then . "${HOME}/opt/google-cloud-sdk/completion.bash.inc"; fi

gcloud_auth() {
  rm -rf "/tmp/${USER}*"
  gcloud auth login --no-launch-browser
}