#!/usr/bin/env bash

# The next line updates PATH for the Google Cloud SDK.
if [ -f "${HOME}/opt/google-cloud-sdk/path.bash.inc" ]; then . "${HOME}/opt/google-cloud-sdk/path.bash.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "${HOME}/opt/google-cloud-sdk/completion.bash.inc" ]; then . "${HOME}/opt/google-cloud-sdk/completion.bash.inc"; fi

gcloud_auth() {
  rm -rf "/tmp/${USER}*"
  gcloud auth login --no-launch-browser
  
  gcloud config unset compute/region
  gcloud config set project "$(gcloud projects list | grep dev | awk '{print $1}')"

  if command -v docker > /dev/null 2>&1; then
    gcloud --quiet auth configure-docker
  fi
}

findhostname () {
    PROJECT=$(getProjectByEnv $1)
    ZONE_NAME=$(PYENV_VERSION=2.7.9 gcloud --project $PROJECT dns managed-zones list | tail -n +2 | fzf | cut -d ' ' -f 1)
    HOSTNAME=$(PYENV_VERSION=2.7.9 gcloud --project $PROJECT dns record-sets list -z $ZONE_NAME | tail -n +2 | fzf | cut -d ' ' -f 1 | rev | cut -d '.' -f 2- | rev)
    echo "https://$HOSTNAME"
}
