#!/usr/bin/env bash

if [[ -f ${HOME}/opt/bin/delta ]]; then
  export GIT_PAGER="delta --dark"
fi

if [[ -f "${HOME}/opt/bash-completion.d/git" ]]; then
    source "${HOME}/opt/bash-completion.d/git";
fi
