#!/usr/bin/env bash

if command -v gpg > /dev/null 2>&1; then
    export GPG_TTY=$(tty)

    cipher_for() {
        if [[ ${#} -lt 2 ]]; then
            printf '%bUsage: cipher_for GITHUB_USERNAME FILE_TO_ENCRYPT%b\n' "${RED}" "${RESET}"
            return 1
        fi

        local TEMP_GNUPGHOME
        TEMP_GNUPGHOME="$(mktemp -d)"

        local PUBLIC_KEY
        PUBLIC_KEY="$(mktemp)"

        curl --disable --silent --show-error --location --max-time 10 "https://github.com/${1}.gpg" >"${PUBLIC_KEY}"
        gpg --homedir "${TEMP_GNUPGHOME}" --import "${PUBLIC_KEY}"

        local RECIPIENT
        RECIPIENT="$(gpg --homedir "${TEMP_GNUPGHOME}" --list-keys --with-colons | grep uid | awk -F: '{print $10}' | uniq | fzf --height=20 --ansi --reverse --prompt "Email:")"

        gpg --homedir "${TEMP_GNUPGHOME}" --encrypt --recipient "${RECIPIENT}" "${2}"

        rm -rf "${TEMP_GNUPGHOME}" "${PUBLIC_KEY}"
    }
fi
