#!/usr/bin/env bash

if [[ -f "${HOME}/opt/bash-completion.d/kubectl" ]]; then
    source "${HOME}/opt/bash-completion.d/kubectl";
    alias __kubectl_last_events="kubectl get event --sort-by=’.lastTimestamp"
    alias k="${HOME}/opt/bin/kubectl"
    complete -o default -F __start_kubectl k
fi

if [[ -f "${HOME}/opt/bash-completion.d/kubemux" ]]; then
    source "${HOME}/opt/bash-completion.d/kubemux";
fi

if command -v kubectl > /dev/null 2>&1; then
  alias __k8s_pods_delete_fast="kubectl delete pods --grace-period=0"
  alias __k8s_pods_sort="kubectl get pods --sort-by=.metadata.creationTimestamp"
  alias __k8s_deploy_show_labels="kubectl get deploy --show-labels"
fi

__k8s_enable_prompt_display () {
  export DOTFILES_PROMPT_KUBE=true
}

__k8s_disable_prompt_display () {
  export DOTFILES_PROMPT_KUBE=false
}

__k8s_mktemp_kubeconfig() {
  KUBECONFIG_TMP=$(mktemp)
  cp "${KUBECONFIG:-${HOME}/.kube/config}" "${KUBECONFIG_TMP}"
  export KUBECONFIG="${KUBECONFIG_TMP}"

  printf "Run kubectl for %s\n" $KUBECONFIG

  __k8s_enable_prompt_display
  kubectx
}

__k8s_pods_by_node() {
  local K8S_NODE
  K8S_NODE=$(k get nodes --no-headers=true -o custom-columns=":metadata.name" | fzf --height=20 --ansi --reverse --select-1)
  kubectl get pods --all-namespaces -o wide --field-selector spec.nodeName=${K8S_NODE}
}
