#!/usr/bin/env bash

alias mainfra="cd ${HOME}/code/MeilleursAgents/MA-Infra"

if [[ -e "${HOME}/code/MeilleursAgents/MA-Infra/tools/gssh/gssh.sh" ]]; then
  source "${HOME}/code/MeilleursAgents/MA-Infra/tools/gssh/gssh.sh"
fi

if [[ -e "${HOME}/code/MeilleursAgents/MA-Infra/tools/vault/vault.sh" ]]; then
  alias vault.sh="${HOME}/code/MeilleursAgents/MA-Infra/tools/vault/vault.sh"
fi

start_instance() {
  gcloud --project ma-dev2 compute instances start "${1:-bdronneau}-developers-1c-0"
}
