#!/usr/bin/env bash

if command -v pyenv > /dev/null 2>&1; then
  export PYENV_VIRTUALENV_DISABLE_PROMPT=1
  export PYENV_ROOT="$HOME/opt/pyenv/"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi
