#!/usr/bin/env bash

if [[ -d "${HOME}/opt/pyenv/" ]]; then
  export PYENV_VIRTUALENV_DISABLE_PROMPT=1
  export PYENV_ROOT="$HOME/opt/pyenv/"
  export PATH="${HOME}/opt/pyenv/shims:${PATH}"

  if command -v pyenv > /dev/null 2>&1; then
    PYENV_RETRIEVE_VERSION="$(pyenv --version | awk  '{ print $2 }')"
    export PATH="${HOME}/opt/pyenv/${PYENV_RETRIEVE_VERSION}/bin:${PATH}"
  fi

  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi
