#!/usr/bin/env bash

[[ -z "${PS1:-}" ]] && return

set_locale() {
  local LOCALES=("en_US.UTF-8" "en_US.utf8" "C.UTF-8" "C")
  local ALL_LOCALES
  ALL_LOCALES="$(locale -a)"

  for locale in "${LOCALES[@]}"; do
    if [[ "$(echo "${ALL_LOCALES}" | grep -c "${locale}")" -eq 1 ]]; then
      export LC_ALL="${locale}"
      export LANG="${locale}"
      export LANGUAGE="${locale}"

      return
    fi
  done

  return 1
}

source_all() {
  local BASHRC_PATH
  BASHRC_PATH="$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null || realpath "${BASH_SOURCE[0]}" 2>/dev/null || echo "${BASH_SOURCE[0]}")"
  local DOTFILES_PATH
  DOTFILES_PATH="$(dirname "${BASHRC_PATH}")"

  local LC_ALL="C"
  local LANG="C"

  for file in "${DOTFILES_PATH}/../sources/"*; do
    [[ -r "${file}" ]] && [[ -f "${file}" ]] && source "${file}"
  done
}

set_locale
source_all

if [[ -e "${HOME}/.localrc" ]]; then
  source "${HOME}/.localrc"
fi

unset -f set_locale
unset -f source_all
