# Configure color for terminal
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Display activity
set -g monitor-activity on
set -g visual-activity off

# Count from 1 instead of 0, and renumber on close
set -g base-index 1
set -g renumber-windows on
setw -g pane-base-index 1
# Increase history limit
set -g history-limit 10000

# set inactive/active window styles
set -g window-style 'fg=colour247,bg=colour236'
set -g window-active-style 'fg=colour250,bg=terminal'

# Pimp status bar
set -g status-left ''
set -g status-right '#[fg=colour2,bg=colour235] #[fg=colour222,bg=colour238] #H '

# Automatically rename a window based on the current directory
set-window-option -g automatic-rename on
set-window-option -g automatic-rename-format "#{b:pane_current_path}"

# Pane formating
# set -g pane-border-status top
set -g pane-border-status off
# set -g pane-border-format "#{pane_index} #{pane_title}"
bind-key r command-prompt -p "Pane name:" "select-pane -T '%%'"
