#!/usr/bin/env bash

export DOTFILES__PACKAGES=true
export DOTFILES__FIRST=true
export DOTFILES_CURLIE=true
export DOTFILES_FZ=true
export DOTFILES_FZF=true
export DOTFILES_GCLOUD=true
export DOTFILES_GIT=true
export DOTFILES_GITOPS=true
export DOTFILES_GOLANG=true
export DOTFILES_GOPASS=true
export DOTFILES_GPG=true
export DOTFILES_HELM=true
export DOTFILES_JQ=true
export DOTFILES_KUBECTL=true
export DOTFILES_PYENV=true
export DOTFILES_SHELLCHECK=true
export DOTFILES_SOFTWARES=true
export DOTFILES_TFSWITCH=true
export DOTFILES_TGSWITCH=true
export DOTFILES_TMUX=true
export DOTFILES_VAULT=true
export DOTFILES_YQ=true
export DOTFILES_Z=true
