name: Git
on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run shellcheck
        run: |
          shellcheck install/*.sh
          shellcheck init.sh
